name: Barracuda Webhook Reporter

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  report-malicious-ips:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Bad-Ip

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run barracuda script
        env:
          BLOCKLIST_URL: ${{ secrets.BLOCKLIST_URL }}
          WEBHOOK_URL_IP: ${{ secrets.WEBHOOK }}
        run: python barracuda.py

      - name: Commit updated logs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add logs/* || echo "Aucun fichier à ajouter"
          git commit -m "Mise à jour des logs IPs $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "Aucun changement"
          git push
