name: Barracuda Webhook Reporter

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  report-malicious-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run barracuda script
        working-directory: Bad-Ip
        env:
          BLOCKLIST_URL: https://raw.githubusercontent.com/duggytuxy/Data-Shield_IPv4_Blocklist/refs/heads/main/prod_data-shield_ipv4_blocklist.txt
          WEBHOOK_URL_IP: ${{ secrets.WEBHOOK_URL_IP }}
        run: |
          mkdir -p logs
          python barracuda.py

      - name: Commit logs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "logs: update malicious IPs [skip ci]"
          file_pattern: 'Bad-Ip/logs/seen_ips.log'
