name: VeilleCyber

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 08h00
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (avec html_clean)
        run: |
          pip install 'lxml[html_clean]'
          pip install -r Veillecyber/requirements.txt

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MISTRAL_API_ENDPOINT: ${{ secrets.MISTRAL_API_ENDPOINT }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: python Veillecyber/main.py
