name: VeilleCyber

on:
  schedule:
    - cron: '0 6 * * *'  # Exécution quotidienne à 08h00 heure française (UTC+2)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Veillecyber

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2-dev \
            libxslt1-dev \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libxmlsec1-dev  # Nouvelle dépendance
    
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt

      - name: Run cybersecurity monitoring
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: python main.py

      - name: Commit and push updates
        if: always()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Déplacement à la racine pour le commit
          cd ..
          
          # Ajout des fichiers générés
          git add Veillecyber/App.log Veillecyber/processed_articles.txt
          
          # Commit seulement si modifications
          git diff --cached --quiet || (git commit -m "📰 Auto-update: Mise à jour des logs et articles traités" && git push)