name: VeilleCyber

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Veillecyber

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          # installe first les modules natifs de newspaper
          pip install newspaper3k lxml_html_clean
          # puis toutes les dépendances listées
          pip install -r requirements.txt

      - name: Run monitoring
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: python main.py

      - name: Commit results
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add App.log processed_articles.txt || true
          git diff --quiet --staged || (git commit -m "Auto-update logs" && git push)
