name: VeilleCyber

on:
  schedule:
    - cron: '0 6 * * *'  # 08h00 heure française (UTC+2 en été)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Veillecyber

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system deps
        run: sudo apt-get install -y libxml2-dev libxslt1-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitoring
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: python main.py

      - name: Commit results
        if: always()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add App.log processed_articles.txt
          git diff --cached --quiet || (git commit -m "Auto-update logs" && git push)