name: VeilleCyber

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 08h00 (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pour avoir accès à l'historique complet

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          pip install 'lxml[html_clean]'
          pip install -r Veillecyber/requirements.txt

      - name: Run script
        working-directory: Veillecyber
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MISTRAL_API_ENDPOINT: ${{ secrets.MISTRAL_API_ENDPOINT }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Veillecyber/App.log Veillecyber/processed_articles.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update logs and processed articles" && git push)
